video_name: caldot2 
full_name: caldot2
dataset_group: blazeit
w: 720
h: 480
seed: 100
start_frame: 0   # 刨除预处理的视频片段的开始帧
end_frame: 32850   # 结束间隔
fps: 15
skip_frames: 60    # 出现空帧的初始采样间隔
max_gap_time: 5     # 最大采样间隔(防止因为一些慢速车辆导致过长的间隔，忽略掉一些快速驶过的车辆)
min_gap_time: 2     # 采样间隔的最小值(防止出现采样的帧正好在车辆出现周期的末端)

traj_dist_min: 50  # 轨迹跨越距离的最小值
thresh_len: 25      # 轨迹持续时间的最小值 fps*1.5
max_len: 300        # 轨迹持续时间的最大值 fps*20
dis_thresh: 1250    # 确定分配轨迹距离的最小值
difference_thresh: 0.0001 # 判断两帧之间是否为同一帧
differ_abs_thresh: 64

iou_thresh: 0.45               # 蒸馏检测模型判断目标的IoU阈值
conf_thresh: 0.3             # 蒸馏检测模型判断目标的置信度阈值
stop_iou_thresh: 0.7          # 通过IoU判断跨帧车辆是否静止
intersect_overlap_thresh: 0.7 # 判断预测轨迹和匹配车辆的预测轨迹是否为同一条的时间跨度重合的阈值
image_thresh_score: 0.999      # Reid 模型的阈值 这里由于triplet loss的原因，阈值设置的很高
# 由于检测器精度的问题，需要忽略的一些区域
ignore_region: []
# ignore_region: []
# 车辆进入/离开画面的区域，用于区分聚类之后的轨迹
stop_area : [[0,309,93,363],[173,257,258,298],[289,248,401,299],[11,373,220,479]]

car_count: 3
truck_count: 2
bus_count: 0