video_name: jackson 
full_name: Jackson_Town
dataset_group: blazeit
w: 1920
h: 1080

seed: 100
start_frame: 10800
end_frame: 108000
fps: 30
skip_frames: 180
max_gap_time: 8
min_gap_time: 4

traj_dist_min: 100 # 轨迹最短长度
thresh_len: 45     # fps*1.5
max_len: 600       # fps*20
dis_thresh: 3200    # 确定分配轨迹距离的最小值
difference_thresh: 0.001 # 判断两帧之间是否为同一帧
differ_abs_thresh: 64  # 越低越严格 过滤越少

iou_thresh: 0.5
conf_thresh: 0.5
stop_iou_thresh: 0.7
intersect_overlap_thresh: 0.7
image_thresh_score: 0.85      # filter模型使用 0.8
# 最后1个是长时间静止的车辆
ignore_region: [[512, 565, 549, 592],[993, 512, 1088, 588],[1230.0, 512.0, 1374.0, 588.0]]
# 左侧出入口/上侧出入口/下右侧出入口/下左侧出入口/右侧出入口
stop_area : [[430,550,750,700],[1550,450,1800,580],[900,900,1180,1080],[0,800,630,1080],[1800,600,1920,770]]

car_count: 3
truck_count: 1
bus_count: 0